### ISSUE TITLE
Typing dependency breaks deployments in AWS lambda

### ISSUE THREAD

**Issue by jns** [SemaphoreSolutions/s4-clarity-lib#26]
The explicit dependency on typing is no longer required given typing is part of the python Standard Library.  When deploying this package in AWS lambda via the serverless application model, the order of dependency loading generates an error `type object 'Callable' has no attribute '_abc_registry'`.  Is it possible to remove the explicit dependency on Typing for Python versions >= 3.5

**Comment by smallsco** [comment]
This has been fixed in v1.3.1!
